version: '3.7'

volumes:
  app-postgres-data:

networks:
  my-net:
    name: my-net

services:
  user_management:
    container_name: user_management
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    ports:
      - '3000:3000'
    command: ['sh', '-c', 'ls && npm install && npm run start:dev']
    env_file:
      - .env
    networks:
      - my-net

  app-postgres:
    container_name: app-postgres
    restart: always
    image: postgres
    volumes:
      - app-postgres-data:/data/db
    environment:
      - POSTGRES_DB=user_management
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123456
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - '5432:5432'
    networks:
      - my-net

  # app-pg:
  #   container_name: app-pg
  #   restart: always
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=admin123456
  #     - PGADMIN_DEFAULT_PASSWORD=admin123456
  #     - PGADMIN_DEFAULT_EMAIL=pedram.aghasian@yahoo.com
  #   ports:
  #     - '80:80'
  #   networks:
  #     - my-net
